examples/config-provider/config-provider.md
src/_util/forwardRefWithStatics.ts
src/_util/useConfig.ts
src/config-provider/ConfigContext.tsx
src/config-provider/ConfigProvider.tsx
src/config-provider/index.ts
src/config-provider/type.ts

feat: add config-provider

---

docs/mobile/mobile.config.js
docs/site/site.config.js
package.json
src/index.ts
src/radio/Radio.tsx
src/radio/RadioGroup.tsx
src/radio/_example/base.jsx
src/radio/_example/group.jsx
src/radio/_example/index.jsx
src/radio/index.ts
src/radio/radio.md
src/radio/style/css.js
src/radio/style/index.js
src/radio/type.ts
src/radio/useDefault.ts

feat(radio): Radio组件实现

---

package.json
src/button/Button.tsx
src/button/_example/icon.jsx

feat(button component): button component support icon

---

src/grid/Grid.tsx
src/grid/GridItem.tsx
src/grid/_example/badge.tsx
src/grid/_example/base.jsx
src/grid/_example/border.jsx
src/grid/_example/layout.jsx
src/grid/_example/normal.jsx
src/grid/grid.md
src/grid/type.ts

Grid api变更、demo修改

---

src/radio/Radio.tsx
src/radio/RadioGroup.tsx
src/radio/radio.md

* 修改类名前缀为 config 配置内容
* 修改组件文档，使用 BASE_DOC 标记

feat(radio): radio组件文档及类名前缀修复

---

.eslintrc.js
package.json
src/input/Input.tsx

fix(eslint): add new rule & fix it

---

site/web/site.config.js
src/back-top/_example/base.jsx

fix(back-top): site config & import path

---

src/button/__tests__/__snapshots__/button.test.tsx.snap

fix(button): fix button component unit test error

---

site/mobile/mobile.config.js
site/web/site.config.js
src/_util/delay.ts
src/_util/getScrollParent.ts
src/index.ts
src/pull-down-refresh/PullDownRefresh.tsx
src/pull-down-refresh/_example/base.jsx
src/pull-down-refresh/_example/index.jsx
src/pull-down-refresh/_example/loading-texts.jsx
src/pull-down-refresh/_example/style/index.less
src/pull-down-refresh/_example/timeout.jsx
src/pull-down-refresh/index.ts
src/pull-down-refresh/pull-down-refresh.md
src/pull-down-refresh/style/css.js
src/pull-down-refresh/style/index.js
src/pull-down-refresh/type.ts

- feat(pull-down-refresh): 新增pull-down-refresh组件

feat(pull-down-refresh): 新增pull-down-refresh组件

---

site/web/site.config.js
src/checkbox/CheckboxGroup.tsx
src/checkbox/_example/base.jsx
src/checkbox/_example/group.jsx
src/checkbox/_example/icon.jsx
src/checkbox/_example/indeterminate.jsx
src/checkbox/_example/index.jsx
src/checkbox/_example/max.jsx
src/checkbox/_example/right.jsx
src/checkbox/checkbox.md
src/checkbox/type.ts

feat(checkbox): demo 优化

---

src/back-top/_example/base.jsx

feat(backtop): update example

---

src/icon/icon.md

docs(icon): 更新 Icon 组件文档

---

site/mobile/mobile.config.js
src/swipe-cell/_example/bind.jsx
src/swipe-cell/_example/content.jsx
src/swipe-cell/_example/event.jsx
src/swipe-cell/_example/index.jsx
src/swipe-cell/_example/left-card.jsx
src/swipe-cell/_example/left-more-menu.jsx
src/swipe-cell/_example/left-one-menu.jsx
src/swipe-cell/_example/left-two-menu.jsx
src/swipe-cell/_example/style/base.less

- docs(swipe-cell): 补充swipe-cell示例代码

docs(swipe-cell): 补充swipe-cell示例代码

---

site/mobile/mobile.config.js
site/web/site.config.js
src/avatar-group/AvatarGroup.tsx
src/avatar-group/AvatarGroupContext.tsx
src/avatar-group/index.ts
src/avatar-group/style/css.js
src/avatar-group/style/index.js
src/avatar/Avatar.tsx
src/avatar/_example/adjust.jsx
src/avatar/_example/index.jsx
src/avatar/_example/shape.jsx
src/avatar/_example/size.jsx
src/avatar/_example/style/index.less
src/avatar/_example/type.jsx
src/avatar/avatar.md
src/avatar/hooks/useSizeHooks.ts
src/avatar/index.ts
src/avatar/style/css.js
src/avatar/style/index.js
src/avatar/type.ts
src/index.ts

feat(avatar): 增加 avatar 组件的基础实现
feat(avatar): 增加 avatar-group 的实现
feat(avatar-group): 增加 avatar-group 组件 样式定义
docs(avatar): 增加 avatar 示例
feat(avatar): 增加完善 avatar 能力
feat(avatar-group): 增加 avatar-group 实现
fix(avatar-group): 修复 avatar-group 错误导出
feat(avatar): 增加 avatar/avatar-group 的导出
docs(avatar): 增加 avatar 文档示例
- feat(avatar): 增加 avatar / avatar-group 组件，完善文档示例

feat(avatar): init avatar docs and type

---

src/image/_example/base.jsx
src/image/_example/error.jsx
src/image/_example/fit.jsx
src/image/_example/index.jsx
src/image/_example/lazy.jsx
src/image/_example/loading.jsx
src/image/_example/position.jsx
src/image/_example/shape.jsx
src/image/_example/style/index.less

- docs(image): update image component docs

docs(image): update image component docs

---

src/divider/Divider.tsx

refactor(divider): divider 用NativeProps包装 && 重构内部实现

---

src/dialog/_example/confirm.jsx
src/dialog/_example/feedback.jsx
src/dialog/_example/index.jsx
src/dialog/_example/input.jsx
src/dialog/_example/style/index.less

- docs(dialog): dialog component docs update

docs(dialog): dialog component docs update

---

src/stepper/index.tsx

fix(stepper): 缺少组件使用到的类型的导出

---

src/divider/index.ts

fix(divider): 缺少组件使用的类型导出

---

src/tabs/_example/base.jsx
src/tabs/_example/bottom.jsx
src/tabs/_example/horizontal.jsx
src/tabs/_example/index.jsx
src/tabs/_example/noline.jsx
src/tabs/_example/scroll.jsx
src/tabs/_example/size.jsx
src/tabs/_example/style.less
src/tabs/_example/vetical.jsx
src/toast/_example/base.jsx
src/toast/_example/icon.jsx
src/toast/_example/iconText.jsx
src/toast/_example/index.jsx
src/toast/_example/position.jsx
src/toast/_example/style.less
src/toast/_example/text.jsx

fix(修改tabs和toast的demo样式): 修改tabs和toast的demo样式

---

src/back-top/Backtop.tsx
src/back-top/_example/base.jsx

- fix(backtop): optimize backtop

feat(backtop): optimize backtop

---

site/mobile/mobile.config.js
site/web/site.config.js
src/index.ts
src/skeleton/Skeleton.tsx
src/skeleton/_example/avatar-text.jsx
src/skeleton/_example/base.jsx
src/skeleton/_example/flashed.jsx
src/skeleton/_example/gradient.jsx
src/skeleton/_example/index.jsx
src/skeleton/_example/pic-text.jsx
src/skeleton/_example/style/index.less
src/skeleton/index.ts
src/skeleton/skeleton.md
src/skeleton/style/css.js
src/skeleton/style/index.js
src/skeleton/type.ts

feat(skeleton): add skeleton component

---

site/mobile/mobile.config.js
site/web/site.config.js
src/_util/helper.ts
src/index.ts
src/textarea/Textarea.tsx
src/textarea/_example/autosize.jsx
src/textarea/_example/base.jsx
src/textarea/_example/events.jsx
src/textarea/_example/index.jsx
src/textarea/_example/maxcharacter.jsx
src/textarea/_example/maxlength.jsx
src/textarea/_example/type.jsx
src/textarea/index.ts
src/textarea/style/css.js
src/textarea/style/index.js
src/textarea/textarea.md
src/textarea/type.ts

feat(textarea): add textarea components

---

src/cell-group/CellGroup.tsx
src/cell/Cell.tsx
src/cell/_example/single.jsx

feat(cell): optimize cell & cell-group

---

src/textarea/Textarea.tsx
src/textarea/_example/events.jsx
src/textarea/_example/index.jsx
src/textarea/_example/label.jsx
src/textarea/_example/maxcharacter.jsx
src/textarea/_example/maxlength.jsx
src/textarea/_example/type.jsx

fix(textarea): support label && update style

---

DEVELOP_GUIDE.md

docs: 补充文档

---

src/back-top/Backtop.tsx
src/back-top/_example/base.jsx
src/back-top/_example/style/index.less

- fix(backtop): 更新backtop示例页&优化backtop组件

fix(backtop): optimize backtop example

---

src/popup/Popup.tsx
src/popup/_example/base.jsx
src/popup/defaultProps.ts
src/popup/popup.md
src/popup/type.ts

Popup组件透传Overlap属性

---

site/mobile/mobile.config.js
site/web/site.config.js
src/index.ts
src/tab-bar/TabBar.tsx
src/tab-bar/TabBarContext.tsx
src/tab-bar/TabBarItem.tsx
src/tab-bar/_example/base.jsx
src/tab-bar/_example/icon-text.jsx
src/tab-bar/_example/mobile.jsx
src/tab-bar/_example/pure-icon.jsx
src/tab-bar/_example/style/index.less
src/tab-bar/_example/text-spread.jsx
src/tab-bar/index.ts
src/tab-bar/style/css.js
src/tab-bar/style/index.js
src/tab-bar/tab-bar.md
src/tab-bar/type.ts
src/tab-bar/useTabBarCssTransition.ts

feat: tabbar component

---

src/slider/Marks.tsx
src/slider/Slider.tsx
src/slider/_example/base.jsx
src/slider/_example/mark.jsx
src/slider/_example/style/index.less

修复 Slider 样式问题

---

site/web/Demo.jsx
src/tag/_example/checkable.jsx
src/tag/_example/closable.jsx
src/tag/_example/ellipsis.jsx
src/tag/_example/shape.jsx
src/tag/_example/size.jsx
src/tag/_example/theme.jsx
src/tag/_example/variant.jsx

修复 /mobile-react/demos/* 路径无法加载组件
- fix(tag): demos路径不可加载组件

fix(tag): demos路径不可加载组件

---

src/stepper/Stepper.tsx
src/stepper/_example/base.jsx
src/stepper/_example/index.jsx

修复 Stepper 样式问题

---

src/swipe-cell/_example/left-more-menu.jsx

fix [165](https://github.com/TDesignOteam/tdesign-mobile-react/issues/165)
- fix(swipe-cell):: 修复example警告色按钮配置错误

fix: 修改example警告色按钮配置错误

---

site/mobile/components/DemoBlock.jsx
site/mobile/components/style/index.less
src/button/__tests__/__snapshots__/button.test.tsx.snap
src/checkbox/Checkbox.tsx
src/checkbox/_example/base.jsx
src/checkbox/_example/right.jsx

修复 Checkbox 样式问题

---

src/switch/_example/base.jsx
src/switch/_example/desc.jsx

fix(switch): update demo

---

src/grid/Grid.tsx
src/grid/GridContext.tsx
src/grid/GridItem.tsx
src/grid/_example/base.jsx
src/grid/_example/style/index.less
src/grid/defaultProps.ts
src/grid/grid.md
src/grid/type.ts

fix #183 
fix #184 
1. 重构了 grid, grid-item 同步 mobile-vue 内容
2. 同步 mobile 演示 demo 与设计稿保持一致

WIP: 修复 grid 组件演示问题

---

src/radio/Radio.tsx
src/radio/_example/icon.jsx
src/radio/_example/index.jsx
src/radio/_example/leftStrokeLine.jsx
src/radio/_example/rightStrokeLine.jsx
src/radio/_example/status.jsx
src/radio/radio.md
src/radio/type.ts

修复 Radio 视觉问题

---

src/rate/_example/base.jsx
src/rate/_example/disabled.jsx
src/rate/_example/size.jsx
src/rate/_example/text.jsx
src/rate/defaultProps.ts
src/rate/rate.md

fix(rate): using correct style

---

src/steps/Steps.tsx

feat: steps组件增加separator api

---

src/swiper/Swiper.tsx

fix [186](https://github.com/TDesignOteam/tdesign-mobile-react/issues/186)
fix [185](https://github.com/TDesignOteam/tdesign-mobile-react/issues/185)
- fix(swiper):: 修复swiper图片比例及按钮大小

fix: 修复swiper图片比例及按钮大小

---

src/divider/Divider.tsx
src/divider/_example/style/index.less

fix(divider): using correct style

---

src/_util/getContainer.ts
src/common.ts
src/sticky/Sticky.tsx
src/sticky/_example/base.jsx
src/sticky/defaultProps.ts
src/sticky/sticky.md
src/sticky/type.ts

fix #222 
修复 Sticky 使用 container 无法生效的问题

fix(sticky): enable container

---

site/mobile/components/style/index.less

fix: correct demo height

---

src/rate/_example/custom-cell.jsx

fix(rate): fix example

---

src/back-top/Backtop.tsx
src/back-top/_example/base.jsx

resolve #151, #152
- fix(backtop): fix example & z-index

fix(backtop): fix example & z-index

---

src/cell/Cell.tsx
src/cell/cell.md
src/cell/defaultProps.ts

#177 
fix #177 
- fix(Cell): 修复 Cell 组件 右侧 icon 边距问题，且优化 Cell 组件代码

fix(Cell): 修复 Cell 组件 右侧 icon 边距问题，且优化代码

---

src/search/Search.tsx
src/search/_example/click.jsx
src/search/defaultProps.ts
src/search/search.md
src/search/type.ts

fix(search): update demo & properties

---

src/avatar/Avatar.tsx
src/avatar/_example/index.jsx
src/avatar/_example/size.jsx
src/avatar/_example/type.jsx

fix(avatar): make vertical align center

---

src/navbar/_example/index.jsx
src/navbar/_example/style/index.less

fix(navbar): using correct style

---

src/indexes/Indexes.tsx
src/indexes/_example/data.ts
src/indexes/_example/index.tsx
src/indexes/_example/style/index.less

fix(indexes): update title style

---

src/message/Message.tsx
src/message/_example/style/index.less
src/message/_example/types.jsx
src/message/methods.tsx

fix https://github.com/TDesignOteam/tdesign-mobile-react/issues/162
https://github.com/TDesignOteam/tdesign-mobile-react/issues/161
https://github.com/TDesignOteam/tdesign-mobile-react/issues/160
https://github.com/TDesignOteam/tdesign-mobile-react/issues/159
https://github.com/TDesignOteam/tdesign-mobile-react/issues/158
https://github.com/TDesignOteam/tdesign-mobile-react/issues/157
- fix(message): message组件修复样式

fix(message): message组件修复样式

---

src/button/__tests__/__snapshots__/button.test.tsx.snap
src/checkbox/Checkbox.tsx
src/checkbox/_example/index.jsx
src/checkbox/_example/style/index.less

fix(checkbox): remove cell related

---

src/button/__tests__/__snapshots__/button.test.tsx.snap
src/radio/Radio.tsx

fix(radio): remove cell related

---

site/mobile/mobile.config.js
site/web/site.config.js
src/index.ts
src/progress/Progress.tsx
src/progress/_example/base.jsx
src/progress/_example/color.jsx
src/progress/_example/index.jsx
src/progress/_example/style/index.less
src/progress/_example/text.jsx
src/progress/_example/type.jsx
src/progress/defaultProps.ts
src/progress/index.tsx
src/progress/progress.md
src/progress/style/css.js
src/progress/style/index.js
src/progress/type.ts
src/progress/utils.ts

feat: #262 
与tdesign-mobile-vue对齐，实现Progress组件
- feat(Progress): 新增Progress组件

feat: 实现Progrss

---

src/sticky/Sticky.tsx

https://github.com/Tencent/tdesign-mobile-vue/issues/194
修复 fixed 状态下丢失宽度的问题
- fix(Sticky): 修复 fixed 状态下丢失宽度的问题

fix(sticky): add default width for content

---

site/web/site.config.js

docs: update component category

---

src/grid/GridItem.tsx

扩展 grid-item 的 props 使其支持 onClick 等事件
#291 
- feat(Grid): 透传所有非定义的 props 至根元素

feat(grid-item): explore grid-item to pass props

---

src/toast/_example/iconText.jsx
src/toast/_example/index.jsx
src/toast/_example/position.jsx
src/toast/_example/preventScrollThrough.jsx
src/toast/_example/text.jsx

- ☑️ 文档改进
- ☑️ 演示代码改进
由于修改了 tDesign-common 中共用的 md 文件，与 tdesign-mobile-vue 修复升级Toast 示例代码和组件demo 一并升级，相关issue地址：https://github.com/Tencent/tdesign-mobile-vue/issues/413?target=toast
- docs(Toast): 升级 Toast 文档示例代码以及组件demo

docs(Toast): update Toast docs and demo

---

src/checkbox/_example/disable.jsx
src/checkbox/_example/group.jsx
src/checkbox/_example/index.jsx
src/checkbox/_example/style/index.less

#413 
- feat(CheckBox): 更新示例代码

docs(checkbox): update docs and demo

---

site/mobile/mobile.config.js
src/sticky/_example/container.jsx
src/sticky/_example/index.jsx
src/sticky/_example/offsetTop.jsx
src/sticky/_example/style/index.less
src/sticky/sticky.md

docs(sticky): update docs and demo

---

site/mobile/mobile.config.js
src/slider/_example/base.jsx
src/slider/_example/disable.jsx
src/slider/_example/index.jsx
src/slider/_example/mark.jsx
src/slider/_example/range.jsx
src/slider/_example/title.jsx
src/slider/_example/unZero.jsx
src/slider/_example/value.jsx

docs(slider): update docs and demo

---

src/steps/_example/click.jsx
src/steps/_example/index.jsx
src/steps/_example/vertical-readonly.jsx
src/steps/_example/vertical.jsx

docs(steps): update doc and demo

---

src/progress/_example/custom.jsx
src/progress/_example/index.jsx
src/progress/_example/noText.jsx
src/progress/_example/status.jsx
src/progress/_example/strokeWidth.jsx

feat(progress): update progress docs and demo

---

src/checkbox/Checkbox.tsx
src/checkbox/type.ts

无
修复点击 content 无反应的问题
- fix(Checkbox): 修复点击 content 无反应的问题

fix(checkbox): enable user to click content

---

site/web/App.jsx

chore: fix github link

---

.vscode/settings.json
package.json
script/rollup.config.js
src/button/Button.tsx
tsconfig.json

fix:  resolved build error

---

.github/workflows/tag-push.yml

- 支持发版时同步更新main分支，需要将main中受保护分支中移除。

ci: update tag-push.yml

---

package.json
src/button/__tests__/button.test.tsx
src/progress/__tests__/progress.test.tsx
test/utils/index.ts

chore(pnpm): fix lack dependencies

---

.github/workflows/typos-config.toml

chore: fix typo

---

tsconfig.json

基础tsconfig配置不应该忽略example

---

.github/workflows/pr-comment-ci.yml

feat(pr-comment-ci): ci improve

---

.github/workflows/pr-comment-ci.yml

fix(pr-comment-ci): process completed with exit code 1

---

.github/workflows/pr-comment-ci.yml

fix(pr-comment-ci): git push not working

---

src/overlay/Overlay.tsx
src/overlay/_example/base.tsx
src/overlay/style/index.js

相关PR
https://github.com/Tencent/tdesign-common/pull/1875

feat(Overlay): add animation

---

.husky/commit-msg
.husky/pre-commit
.husky/prepare-commit-msg
package.json

chore: update pre-commit

---

.github/workflows/pr-comment-ci.yml

fix(pr-comment-ci): resolve update-common exit status 128

---

.github/workflows/pr-comment-ci.yml

chore: adjust pr-comment-ci

---

src/cell/cell.md

docs: update cell.md

---

src/divider/Divider.tsx
src/divider/__tests__/divider.test.tsx

feat(Divider):  use parseTNode render content & children

---

package.json

- feat(Icon): 更新图标库版本到 `0.3.5` ，`lock-on` 图标存在更新

chore: upgrade tdesign-icons-react 0.3.5

---

src/input/defaultProps.ts
src/input/input.en-US.md
src/input/input.md
src/input/type.ts

- https://github.com/TDesignOteam/tdesign-api/pull/405

docs(input): fix status default value

---

.github/workflows/pr-comment-ci.yml
package.json

chore: update pr-comment-ci

---

site/plugin-tdoc/md-to-react.js

slider组件
- other: 修复组件 `api` 文档中含模版字符串时渲染失败的问题

fix: fix api doc parsing failure

---

src/stepper/Stepper.tsx

fix(Stepper): fix the problem of not supporting direct input

---

src/count-down/hooks/useCountDown/useCountDown.ts
test/snap/__snapshots__/csr.test.jsx.snap

fix #540 
- fix(CountDown): 修复毫秒级计算器计算错误

fix(count-down): use raf not setInterval

---

package.json

pnpm dev
```
The following dependencies are imported but could not be resolved:
@popperjs/core (imported by /Users/liweijie/Project/tdesign/tdesign-mobile-react/src/popover/Popover.tsx)
dayjs/locale/zh-cn (imported by /Users/liweijie/Project/tdesign/tdesign-mobile-react/src/_common/js/global-config/mobile/locale/zh_CN.ts)
Are they installed?
```

chore: fix deps

---

site/web/App.jsx

chore: replace version request

---

package.json
test/snap/__snapshots__/csr.test.jsx.snap

chore(deps): add tinycolor2

---

src/color-picker/index.ts
src/color-picker/style/css.js
src/color-picker/style/index.js

- fix(ColorPicker):  修复组件 `es` 产物缺样式文件入口

fix(ColorPicker): fix es product errors

---

src/toast/Toast.tsx
src/toast/_example/theme.tsx
src/toast/constant.ts
src/toast/index.ts
src/toast/methods.tsx
src/toast/toast.en-US.md
src/toast/toast.md
src/toast/type.ts

- feat(Toast): 新增 `warning` 主题

feat(toast): add warning theme support

---

package.json
site/mobile/App.jsx
site/style/mobile/demo.less
site/style/mobile/index.less
site/web/App.jsx
site/web/main.jsx
src/avatar/_example/style/index.less
src/button/_example/style/index.less
src/count-down/_example/style/index.less
src/dialog/_example/style/index.less
src/divider/_example/style/index.less
src/drawer/_example/style/index.less
src/fab/_example/style/index.less
src/indexes/_example/style/index.less
src/layout/_example/style/index.less
src/message/_example/style/index.less
src/notice-bar/_example/style/index.less
src/overlay/_example/style/index.less
src/picker/_example/style/index.less
src/pull-down-refresh/_example/style/index.less
src/result/_example/style/index.less
src/side-bar/_example/style/index.less
src/skeleton/_example/style/index.less
src/slider/_example/style/index.less
src/swiper/_example/style/index.less
src/tag/_example/style/index.less
src/toast/_example/style/index.less

feat(site): support theme generator

---

src/index.ts
src/side-bar/_example/base.tsx
src/side-bar/_example/custom.tsx
src/side-bar/_example/switch.tsx
src/side-bar/_example/with-icon.tsx

fix(SideBar): fix component not exported

---

src/slider/Slider.tsx

https://github.com/Tencent/tdesign-mobile-vue/pull/1811
https://github.com/Tencent/tdesign-common/pull/2120
- fix(Slider): `marks` 属性不支持 `()=>TNode` 渲染的问题 

fix(slider): marks prop does not support ()=>TNode

---

src/overlay/Overlay.tsx
src/overlay/_example/base.tsx
src/overlay/overlay.en-US.md
src/overlay/overlay.md
src/overlay/type.ts

fix #592 
https://github.com/TDesignOteam/tdesign-api/pull/617
- feat(Overlay): 新增遮罩动画系列回调函数，包括 `onOpen`、`onOpened`、`onClose` 和 `onClosed` 事件

feat(Overlay): add overlay animation series callback func

---

CHANGELOG.md

- other(site): 按照统一的、新的日志书写规则标准化日志文档

docs(changelog): standardize according to the new rules

---

src/steps/__tests__/__snapshots__/demo.test.tsx.snap

chore: update snapshot

---

README.md
site/mobile/App.jsx
site/mobile/components/Home.jsx
site/mobile/components/style/home.less
src/collapse/Collapse.tsx

chore: add home page for demo

---

src/back-top/Backtop.tsx

- fix(back-top): add default value for target

fix(back-top): add default value for target

---

src/sticky/Sticky.tsx

fix #369
- fix(`Sticky`): 修复不生效问题

fix(sticky): fix basic sticky

---

src/popup/Popup.tsx
src/popup/defaultProps.ts
src/popup/popup.en-US.md
src/popup/popup.md
src/popup/type.ts

fix #422
- feat(Popup): 新增 `duration` 属性

feat(popup): add duration props

---

CHANGELOG.md
package.json

chore: publish v0.19.0

---

package.json

chore: 显式声明必需依赖 validator，防止使用 pnpm 时报错

---

site/docs/overview.en-US.md
site/docs/overview.md
site/web/site.config.js

docs(overview): supplement qrcode component content

---

site/web/components/stackblitz/content.js

docs(stackblitz): optimize startup speed

---

.github/workflows/issue-assignees.temp.yml

chore: remove auto assigned workflow

---

src/link/Link.tsx
src/link/__tests__/index.test.tsx

更新测试案例名称， api 是 TNode 的补充 function 单侧

test(link): update test case

---

site/docs/overview.en-US.md
site/docs/overview.md
site/web/site.config.js

- tab-bar 组件示例页面路由与其他端保持一致
- 修复 site.config.js 中单词拼写错误

chore(overview): unified tab-bar component routing path

---

site/test-coverage.js
src/empty/__tests__/empty.test.tsx

新增Empty组件单元测试，更新多组件测试覆盖率数据
re #697

test(empty): empty组件单元测试

---

package.json
site/web/main.jsx

chore: @tdesign/site-components instead of tdesign-site-components

---

site/test-coverage.js
src/overlay/__tests__/overlay.test.tsx

test(overlay): add overlay test

---

site/test-coverage.js
src/result/__tests__/index.test.tsx

Test: Result test

---

README-zh_CN.md
README.md

chore: update group code path
